[package]
name = "metal-compute-shader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metal = "0.26.0"
objc = "0.2.7"
rand = "0.8.5"
ndarray = "0.15"
ndarray-rand = "0.14"