[package]
name = "webgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.17"
bytemuck = "1"
ndarray = "0.15"
ndarray-rand = "0.14"
pollster = "0.3"